DigitalStore/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalStore.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Authorize(Roles = "Admin, Publisher, Marketing Partner")]
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

DigitalStore/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalStore.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

DigitalStore/Controllers/GamesController.cs
using DigitalStore.Models;
using DigitalStore.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalStore.Controllers
{
    public class GamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Game
        public ActionResult Index(int? id)
        {

            var items = db.Games.OrderByDescending(x => x.Id).ToList();
            if (id != null)
            {
                items = items.OrderByDescending(x => x.Id).Where(x => x.GameGenreId == id).ToList();
            }
            return View(items);
        }
        public ActionResult Detail(string alias, int id)
        {
            var item = db.Games.Find(id);
            var countReview = db.Reviews.OrderByDescending(x => x.Id).Where(x => x.GameId == id).Count();    
            ViewBag.CountReview = countReview;
            return View(item);
        }
        public ActionResult GameGenre(string alias, int? id)
        {
            var items = db.Games.ToList();
            if (id > 0)
            {
                items = items.OrderByDescending(x => x.Id).Where(x => x.GameGenreId == id).ToList();
            }
            var genre = db.GameGenres.Find(id);
            if (genre != null)
            {
                ViewBag.GenreName = genre.Name;
            }
            ViewBag.Genre_ID = id;
            return View(items);
        }
        public ActionResult Partail_ItemsByGenreID()
        {
            var items = db.Games.OrderByDescending(x => x.Id).Where(x => x.IsActive && x.IsHome).Take(12).ToList();
            return PartialView(items);
        }

        public ActionResult Partical_GameSale()
        {
            var items = db.Games.OrderByDescending(x => x.Id).Where(x => x.IsHome && x.IsActive && x.IsFeatured).Take(12).ToList();
            return PartialView(items);
        }

        public ActionResult Partical_TopSeller()
        {
            var items = db.Games.OrderByDescending(x => x.Id).Where(x => x.IsHome && x.IsActive && x.IsSale).Take(12).ToList();
            return PartialView(items);
        }

        public ActionResult Partical_NewRelease() 
        {
            var items = db.Games.OrderByDescending(x => x.Id).Where(x => x.IsHome && x.IsActive && x.IsNew).Take(12).ToList();
            return PartialView(items);
        }

        public ActionResult Partial_Related(int gamegenreId, int gameId)
        {
            var item = db.Games.OrderByDescending(x => x.Id).Where(x => x.GameGenreId == gamegenreId && x.Id != gameId).OrderByDescending(x => x.Id).ToList();
            return PartialView(item);
        }

        public ActionResult Partial_Related_Publisher(int gameId, int publisherId)
        {
            var item = db.Games.OrderByDescending(x => x.Id).Where(x => x.Id != gameId && x.PublisherId == publisherId).OrderByDescending(x => x.Id).ToList();
            return PartialView(item);
        }
    }
}

DigitalStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalStore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DigitalStore/Controllers/MenuController.cs
using DigitalStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalStore.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MenuTop() 
        {
            var item = db.Menus.OrderBy(x => x.Id).ToList();
            return PartialView("_MenuTop", item);
        }
        public ActionResult MenuLeft(int? id)
        {
            if (id != null)
            {
                ViewBag.Genre_ID = id;
            }
            var items = db.GameGenres.ToList();
            return PartialView("_MenuLeft", items);
        }
        public ActionResult MenuGameGenre()
        {
            var items = db.GameGenres.ToList();
            return PartialView("_MenuGameGenre", items);
        }

        public ActionResult MenuArrivals()
        {
            var items = db.GameGenres.Take(5).ToList();
            return PartialView("_MenuArrivals", items);
        }
    }
}

DigitalStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

DigitalStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

DigitalStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!-- Slider -->

<div class="main_slider">
    <div class="main_banner_container">
        <img src="~/Content/assets/test/banner5.jpg">
    </div>
</div>

<!-- Banner -->
@Html.Action("MenuGameGenre", "Menu")


<!-- New Arrivals -->

<div class="new_arrivals">
    <div class="container">
        @Html.Action("MenuArrivals", "Menu")
    </div>
</div>

<!-- Deal of the week -->

<div class="deal_ofthe_week">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="deal_ofthe_week_img">
                    <img src="~/Content/assets/test/soulcinder.png" alt="" class="pr-4">
                </div>
            </div>
            <div class="col-lg-6 text-right deal_ofthe_week_col" style="padding-left: 50px;">
                <div class="deal_ofthe_week_content d-flex flex-column align-items-center float-right">
                    <div style="padding-left: 10px;">
                        <div class="section_title">
                            <h2>Ưu đãi trong tuần</h2>
                        </div>
                    </div>
                    
                    <ul class="timer" style="padding-right: 100px;">
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="day" class="timer_num">03</div>
                            <div class="timer_unit">Ngày</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="hour" class="timer_num">15</div>
                            <div class="timer_unit">Giờ</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="minute" class="timer_num">45</div>
                            <div class="timer_unit">Phút</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="second" class="timer_num">23</div>
                            <div class="timer_unit">Giây</div>
                        </li>
                    </ul>
                    <div style="padding-left: 50px;">
                        <div class="red_button deal_ofthe_week_button"><a href="#">Mua ngay</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Best Sellers -->

@Html.Action("Partical_GameSale", "Games")



@Html.Action("Partical_TopSeller", "Games")


@Html.Action("Partical_NewRelease", "Games")