DigitalStore/Models/EF/MarketingPartner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DigitalStore.Models.EF
{
    [Table("tb_MarketingPartner")]
    public class MarketingPartner : CommonAbstract
    {
        public MarketingPartner()
        {
            this.Contracts = new HashSet<Contract>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }

        public ICollection<Contract> Contracts { get; set; }
    }
}

DigitalStore/Areas/Admin/Controllers/MarketingPartnerController.cs
using DigitalStore.Models;
using DigitalStore.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigitalStore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MarketingPartnerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/MarketingPartner
        public ActionResult Index()
        {
            var item = db.MarketingPartners;
            return View(item);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MarketingPartner model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                db.MarketingPartners.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var item = db.MarketingPartners.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MarketingPartner model)
        {
            if (ModelState.IsValid)
            {
                db.MarketingPartners.Attach(model);
                model.ModifiedDate = DateTime.Now;
                db.Entry(model).Property(x => x.Name).IsModified = true;
                db.Entry(model).Property(x => x.Description).IsModified = true;
                db.Entry(model).Property(x => x.ModifiedDate).IsModified = true;
                db.Entry(model).Property(x => x.ModifiedBy).IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.MarketingPartners.Find(id);
            if (item != null)
            {
                db.MarketingPartners.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

DigitalStore/Areas/Admin/Views/MarketingPartner/Add.cshtml
@model DigitalStore.Models.EF.MarketingPartner
@{
    ViewBag.Title = "Thêm đối tác quảng cáo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section Naviheader
{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Publisher" class="nav-link">Danh mục</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}

@section body{
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Thêm Đối tác quảng cáo</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Danh sách đối tác quảng cáo</a></li>
                        <li class="breadcrumb-item active">Thêm mới</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Thông tin thêm mới danh mục</h3>
            </div>
            <div class="card-body">
                <div class="bs-stepper-content">
                    @using (Html.BeginForm("Add", "MarketingPartner", FormMethod.Post, new { }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <!-- your steps content here -->
                        <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên đối tác quảng cáo</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Tên nhà phát hành" })
                                @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Mô tả</label>
                                @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <a href="/Admin/MarketingPartner" class="btn btn-danger">Quay lại</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    }


                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
}

DigitalStore/Areas/Admin/Views/MarketingPartner/Edit.cshtml
@model DigitalStore.Models.EF.MarketingPartner
@{
    ViewBag.Title = "Cập nhật thông tin đối tác quảng cáo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Naviheader
{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Publisher" class="nav-link">Danh sách đối tác quảng cáo</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Cập nhật</a>
        </li>
    </ul>
}

@section body{
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cập nhật thông tin đối tác quảng cáo</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Danh sách đối tác quảng cáo</a></li>
                        <li class="breadcrumb-item active">Cập nhật</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Thông tin đối tác quảng cáo</h3>
            </div>
            <div class="card-body">
                <div class="bs-stepper-content">
                    @using (Html.BeginForm("Edit", "MarketingPartner", FormMethod.Post, new { }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(x => x.Id)
                        <!-- your steps content here -->
                        <div id="logins-part" class="content" role="tabpanel" aria-labelledby="logins-part-trigger">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên đối tác quảng cáo</label>
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "Tên đối tác quảng cáo" })
                                @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Mô tả</label>
                                @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <a href="/Admin/MarketingPartner" class="btn btn-danger">Quay lại</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    }


                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
}

DigitalStore/Areas/Admin/Views/MarketingPartner/Index.cshtml
@model IEnumerable<DigitalStore.Models.EF.MarketingPartner>
@{
    ViewBag.Title = "Trang quản lý đối tác quảng cáo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Naviheader
{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/MarketingPartner" class="nav-link">Danh mục đối tác quảng cáo</a>
        </li>
    </ul>
}
@section body{
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Quản lý đối tác quảng cáo</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Danh sách đối tác quảng cáo</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách đối tác quảng cáo</h3>

                <div class="card-tools">
                    <a href="/Admin/MarketingPartner/Add" class="btn btn-primary">Thêm mới</a>
                </div>
            </div>


            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên đối tác quảng cáo</th>
                            <th>Mô tả</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @if (Model != null && Model.Any())
                        {
                            var i = 1;
                            foreach (var item in Model)
                            {
                                <tr id="trow_@item.Id">
                                    <td>@i</td>
                                    <td>@item.Name</td>
                                    <td>@item.Description</td>
                                    <td>
                                        <a href="/Admin/MarketingPartner/Edit/@item.Id" class="btn btn-sm btn-primary">Sửa</a>
                                        <a href="#" data-id="@item.Id" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                                    </td>
                                </tr>
                                i++;
                            }

                        }
                        else
                        {
                            <tr>
                                <td colspan="4">Không có bản ghi nào</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">

            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
}
@section scripts
{
    <script>
            $(document).ready(function () {
                $('body').on('click', '.btnDelete', function () {
                    var id = $(this).data("id");
                    var conf = confirm("Bạn có muốn xóa danh mục này không ?");
                    if (conf == true) {
                        $.ajax({
                            url: '/Admin/MarketingPartner/Delete',
                            type: 'POST',
                            data: { id: id },
                            success: function (rs) {
                                if (rs.success) {
                                    $('#trow_' + id).remove();
                                }
                                location.reload()
                            }
                        });
                    }
                });
            });
    </script>
}